### PR TITLE
JWT Token security added for socket

### PR DESCRIPTION
**Pull request by vvaldersteins**
JWT socket validation added for the socket.

### CODE REVIEW

**Comment by colinl** [comment]
Will these changes break existing applications?

**Comment by vvaldersteins** [comment]
@colinl they should not break, since by default it's turned off (you have to turn on jwt security through the node), but this is meant for @TotallyInformation for review.

**Comment by colinl** [comment]
Yes, I realise it is for review. My question was intended to be part of the review process.

**Comment by TotallyInformation** [comment]
Hi, sorry I've taken so long to respond to this properly.

I've been thinking a lot about security for uibuilder. I'm not entirely convinced that this is the best approach actually. 

I've already added a middleware capability that allows you to insert JWT or anything else into the *authorisation* process - the important thing is that this should be a standard process across all of your instances of uibuilder nodes and it MUST be tied into an *authentication* so a stand-alone process may not be as good. 

Certainly having the "secret" in the standard node properties is not so good, they need to go into secure settings.

Thanks for this code though. I'm going to keep this here so that I can refer to it as the design progresses.

**Comment by TotallyInformation** [comment]
I've been doing some further research on this subject and I'm getting closer to a proper answer I believe.

Firstly note that custom headers - including JWT - are **only** valid on first connection. This is because the initial connection happens over http(s). But the connection is then "upgraded" if it can be, generally to websockets which is what we want.

However, the websocket standards don't allow for custom headers.

To resolve this, there are two options:

- Add the JWT token to the URL as a parameter

   This works OK - BUT it could result in the token getting caught in caches and this is not good security as it provides long-term exposure which can lead to the ability to brute-force decryption.

   Not necessarily that big a problem in most cases but non-the-less something best avoided if possible.

- Pass the JWT token as data in the websocket message body

   I think that this is likely to be the way to go. It is, at least in theory, more secure as the body of the message will always be encrypted if using https/wss.

So what I'm thinking is that the best approach will be as follows:

- Use the middleware function for the initial handshake - since this can be tied together with the handshake for the ExpressJS web server as well if desired.
- Have a "standard" msg property to hold a security token (normally JWT encoded I expect but it could be something custom if needed).
- Add a helper to uibuilder that checks for the standard token property and hands off to the middleware function. This would let people use a single function for ongoing security checks such as source address validation, session expiry, etc. With minimal effort from the user.

Assuming this approach holds up to scruitiny, I will build this into uibuilder v2.1 or maybe 2.2.

Thanks again for the contribution. Sorry Valters that I haven't used your PR directly but it has certainly helped me slowly get to the bottom of how to do this properly.

Thanks to you as well Colin for your ongoing input.

I will leave this PR open as we are still discussing the approach - once we have a clear way forward and I've documented it in the To Do WIKI entry, I will close it.

**Comment by TotallyInformation** [comment]
Keeping open as I'm getting closer to a proper answer.

**Pull request closed without merging**
