### PR TITLE
uibuilderfe-js.md - Fix link to front-end-library

### PR DESCRIPTION
**Pull request by meeki007**
### A description of the changes proposed in the pull request and why
Update Documentation
Markdown link does not point to valid url. missing .md at end.

### CODE REVIEW

**Comment by TotallyInformation** [comment]
Odd, let me do some more digging. Docsify shouldn't care whether the .md is there or not. Its beer-o-clock right now though and its been a long hard week here. Catch up with you soon.

**Comment by meeki007** [comment]
Dude No rush I will check back in with you if it goes past 7days. Enjoy your weekend. Documentation can wait. I'm looking foward to my double shot of Elijah Craig 94proof small batch in 4hrs (6pm) when I'm done for the day. . . enjoy your beer-o-clock

**Comment by TotallyInformation** [comment]
Never found a bourbon I liked though I've never looked that far. I do like my scotch though. Especially if aged in sherry casks. :-)

**Comment by TotallyInformation** [comment]
Hi, I'm pretty sure that this is a GitHub problem because you are accessing the vNext branch which isn't the documentation branch. If you try to access that link from within uibuilder, it works. When vNext becomes the main branch on publishing, that link will work correctly. So I'm going to close this for now. Thanks.

**Comment by TotallyInformation** [comment]
Consequence of trying to use the GitHub pages from a different branch. Will resolve itself when vNext gets merged into main.

**Pull request closed without merging**
