### PR TITLE
Place frontend files in the according project-path if Node-Red projects are enabled

### PR DESCRIPTION
**Pull request by Thomseeen**
Adressing issue #44.

### Description
The path to the front-end files gets calculated based on wether Node-Reds project feature is enabled or not. If it is not, the path to the files is untouched. If it is, a new path gets choosen based on the active project.
This enabled the git repository that Node-Red automatically initializes in the project folder to also track the uibuilder files.

Projects disabled - FE files at:
`<userDir>/uibuilder`
Projects enabled - FE files at:
`<userDir>/projects/<projectName>/uibuilder`

### Remaining problem
Sorry for my probably not fully correct web-stuff jargon.
I.e. project A with a uibuilder page at `/foo` and project B with a uibuilder page at `/bar`.
If the project is changed during Node-Red runtime from A to B `/foo` is still callable but without any function while `/bar` works as intended. After a Node-Red restart only `/bar` is reachable as the expected behaviour would be. With my limited experience in web-stuff I can't really figure out how to "delete" the webpage of the no longer choosen project.

### Environment used for development and testing

Software       | Version
-------------- | -------
Node.JS        | v10.15.0
npm            | 6.4.1
Node-RED       | v0.19.5
uibuilder node | 1.1.0
uibuilderFE    | 
OS             | Win10 Enterprise and Win10 Pro
Browser        | Firefox 60.4.0esr (64bit)

### CODE REVIEW

**Comment by TotallyInformation** [comment]
Many thanks for this. I will review properly as soon as I can.

The issue you've raised doesn't seem right. I would have thought that changing projects would trigger the shutdown process which does its best to remove all of the ExpressJS paths that have been added.

I will have to have a more detailed look at this. Personally, I don't use projects since they've caused me more problems than they give benefits. You may be aware that I don't generally use a standard installation either as I don't like the global install.

So I will have to set up an environment with projects and then turn on debugging to see what happens when you change project. May take me a bit of time to go through this. Once I've tracked down what is happening I may also need to call on Nick and Dave to work around the issue.

The good news is that this should also help further tidy up the code and processing.

You've also triggered some thoughts about some more optimisations so thanks for that.

In the meantime, a workaround - can't remember whether I mentioned this - would be to create a `link` from the uibuilder/url folder into your project folder so that they can be managed using a single git repo. That won't fix the project swap processing though of course, only the git processing issue you first raised.

**Comment by Thomseeen** [comment]
> The issue you've raised doesn't seem right. I would have thought that changing projects would trigger the shutdown process which does its best to remove all of the ExpressJS paths that have been added.

Well it seems like the HTML/CSS-page still gets loaded (is that a cache thing?) even if the matching project isn't opened anymore but the connection to the actual Node-Red flow/the uibuilder-node isn't there anymore.

> In the meantime, a workaround - can't remember whether I mentioned this - would be to create a `link` from the uibuilder/url folder into your project folder so that they can be managed using a single git repo. That won't fix the project swap processing though of course, only the git processing issue you first raised.

Thanks :) ... but I am perfectly fine for now. I have forked and with the changes everything works fine for my use-case. I can install my variant of uibuilder to other machines and clone the repository of my Node-Red project to them and everything works without having to also manually copy the uibuilder files. Also I don't have to switch projects often and if I have to a Node-Red restart fixes any problems so everythings alright and there is no need to hurry, at least not for me.

**Comment by TotallyInformation** [comment]
Hi Thomas,

Sorry about this - I've discovered a bug that I think was probably causing the issue with project swaps.

Unfortunately, the code changes mean that your PR isn't quite valid now. Could you please merge my changes and update/test? Hopefully it will work now.

Because I was working on uibuilder.js and have made some extensive changes, you will need to review your code carefully.

The error was strange because it wasn't generating any warning or error messages even though a function in uiblib couldn't find a dependent function to call. Anyway, I've split the utility libraries in two which has fixed the issue. Now the app.use paths should actually be moved on closedown.

**Comment by Thomseeen** [comment]
I have adapted your changes and resolved the conflicts in my fork. After testing it looks like it works fine on my end, now even when changing projects. Thanks a lot!

**Comment by TotallyInformation** [comment]
Cool, thanks for that. I will be integrating this into v2. It perhaps isn't quite a breaking change but it is certainly different for anyone using projects.

**Comment by TotallyInformation** [comment]
Hi, I have incorporated your changes into v2 so please feel free to try that out - it is still in testing but you can install from the v2 branch and it should work.

Note that there are some breaking changes in v2 so check out the changelog.

While I haven't directly merged your PR, I've used it to help me add that feature.

I've also added you to the list of contributors - many thanks again for your help.

**Pull request closed without merging**
